### ISSUE TITLE
Create OAuth client ID failed

### ISSUE THREAD

**Issue by ing19872** [biplobsd/yst#11]
I'm getting an error when I'm trying to create an OAuth client ID it's saying that "The request failed because one of the field of the resource is invalid. Tracking number:  c4277841947401659". But I'm very sure that I entered everything correctly according to the guide on the page. Have you encountered this error before can u please help. Thank you.
![Screenshot 2024-05-07 ](https://github.com/biplobsd/yst/assets/82097352/384ba6c1-4e24-44b2-951e-2f1797524431)

**Comment by biplobsd** [comment]
Hey @ing19872 , remove `<` and `>` from the url

Example: 
![image](https://github.com/biplobsd/yst/assets/43641536/28d8963e-0986-4a49-8b2d-496d5b500733)
