### ISSUE TITLE
Subscription failed - "Unable to subscribe this channel"

### ISSUE THREAD

**Issue by R8s6** [biplobsd/yst#9]
Hi,

Thanks for the wonderful extension, it worked a few months back for me, but today when I tried it for a friend, subscription failed with the error being "Unable to subscribe this channel".

Here's how to reproduce it:

1. Logged in to a youtube account, from this extension's drop-down menu, hit the "Collect Channel" button;
2. "Data" were populated;
3. switched to a new youtube account, re-open the drop-down menu on this new youtube page;
5. hit the "Subscribe" button, it would then say "Unable to subscribe this channel" to every collected channel.

I'm running version 1.6 in xpath mode, on Chromium (Version 122.0.6261.69, Arch Linux).

Any ways to troubleshoot / debug?

Thanks!

**Comment by biplobsd** [comment]
@R8s6 Thanks for reporting this issue. I'm now investigating this problem. I'll update you about this issue soon.

**Comment by biplobsd** [comment]
Hello @R8s6, I have push a fix. Could you please check this issue again?

**Comment by R8s6** [comment]
It worked beautifully, thank you so much!

By the way, your documentation is fantastic. As a chromium noob (as I normally use firefox), I never built an extension from git or knew how to install unpacked ones, but following your docs step-by-step, i did it in 2 minutes. Thanks a lot!
